version: '1'

services:
  gc-api:
    hostname: gc-api
    build:
      dockerfile: Dockerfile  
    env_file: .env.dev
    ports:
      - 5000:5000
    restart: "no"

networks:
  default:
    name: gc-development