# fly.toml app configuration file generated for gc-api on 2023-11-13T19:47:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gc-api"
primary_region = "yyz"

[build]

[env]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
